"""empty message

Revision ID: 132349eb2fdc
Revises: aba4b44b6fd9
Create Date: 2023-04-21 00:12:22.539532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132349eb2fdc'
down_revision = 'aba4b44b6fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
