"""empty message

Revision ID: 445fe16af8cf
Revises: a119c543d916
Create Date: 2023-04-20 23:30:28.529261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445fe16af8cf'
down_revision = 'a119c543d916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
